
let clockWidgetInitGui = {
    type: 'Box',
    id: 'clockBox',
    width: '100%',
    height: '100%',
    transition: 'transform 1s',
    children: [
      {
        type: 'Image',
        id: 'clockBackImage',
        width: '100%',
        height: '100%',
        borderRadius: 1000,
        position: 'absolute',
        left: 0,
        top: 0,
        zIndex: 1,
        src:
          'https://i.pinimg.com/originals/eb/ad/bc/ebadbc481c675e0f2dea0cc665f72497.jpg',
      },
      {
        type: 'Box',
        id: 'clockBackShadow',
        width: '100%',
        height: '100%',
        borderRadius: 1000,
        position: 'absolute',
        left: 0,
        top: 0,
        zIndex: 2,
        background: 'rgba(255, 255, 255, 0.5)',
      },
      {
        type: 'Text',
        id: 'clockMsg',
        width: '100%',
        height: 'auto',
        position: 'absolute',
        alignChildren: 'center',
        top: 32,
        zIndex: 3,
        text: 'سلام کیهان',
        transform: 'rotateY(-180deg)',
        display: 'none',
      },
      {
        type: 'Image',
        id: 'weather',
        width: '50%',
        position: 'absolute',
        alignChildren: 'center',
        top: 56,
        right: 56,
        zIndex: 3,
        src:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrRZ2vclesoWZ4DOCjXPzbAvg5VEFEn7OiHQ&usqp=CAU',
        transform: 'rotateY(-180deg)',
        display: 'none',
      },
      {
        type: 'Text',
        id: 'weatherMsg',
        width: '100%',
        height: 'auto',
        position: 'absolute',
        alignChildren: 'center',
        top: 112 + 40 + 24,
        zIndex: 3,
        text: 'نیمه ابری 31 درجه',
        transform: 'rotateY(-180deg)',
        display: 'none',
      },
      {
        type: 'Box',
        id: 'secondHand',
        width: 250,
        height: 25,
        position: 'absolute',
        left: 100,
        top: 'calc(50% - 12.5px)',
        transform: 'rotate(75deg)',
        transition: 'transform 1s',
        zIndex: 3,
        children: [
          {
            type: 'Box',
            id: 'secondImage',
            width: 200,
            height: '100%',
            position: 'absolute',
            left: '50%',
            background: 'rgba(0, 0, 0, 0.75)',
            borderRadius: '50%'
          },
        ],
      },
      {
        type: 'Box',
        id: 'minuteHand',
        width: 450,
        height: 25,
        position: 'absolute',
        left: '0',
        top: 'calc(50% - 12.5px)',
        transform: 'rotate(-135deg)',
        transition: 'transform 1s',
        zIndex: 3,
        children: [
          {
            type: 'Box',
            id: 'minuteImage',
            width: 170,
            height: '100%',
            position: 'absolute',
            left: '50%',
            background: 'rgba(0, 0, 0, 0.75)',
            borderRadius: '50%'
          },
        ],
      },
      {
        type: 'Box',
        id: 'hourHand',
        width: 450,
        height: 25,
        position: 'absolute',
        left: 0,
        top: 'calc(50% - 12.5px)',
        transform: 'rotate(295deg)',
        transition: 'transform 1s',
        zIndex: 3,
        children: [
          {
            type: 'Box',
            id: 'hourImage',
            width: 125,
            height: '100%',
            position: 'absolute',
            left: '50%',
            background: 'rgba(0, 0, 0, 0.75)',
            borderRadius: '50%'
          },
        ],
      },
    ],
};

module.exports = {
  clockWidgetInitGui: clockWidgetInitGui
};